### ISSUE TITLE
verbose not working

### ISSUE THREAD

**Issue by wstoettinger** [ian-hamlin/qrgen#8]
I've tried to get a little bit more debug information because one of my qr-codes is not generating. unfortunately, the flag doesn't have any effect.

i tried:
.\qrgen.exe -v test.csv
.\qrgen.exe -vv test.csv
.\qrgen.exe -vvv test.csv
.\qrgen.exe --verbose test.csv

**Comment by ian-hamlin** [comment]
Hi,

You need to turn on logging before that switch will work, either `-l, --log    `
